/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notes: () => import('#controllers/notes_controller'),
  Password: () => import('#controllers/password_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
